---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
    name: kata-qemu-coco-dev
handler: kata-qemu-coco-dev
overhead:
    podFixed:
        memory: "160Mi"
        cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
