name: Kata Containers CI (manually triggered)
on:
  workflow_dispatch:

jobs:
  kata-containers-ci-on-push:
    uses: ./.github/workflows/ci.yaml
    with:
      commit-hash: ${{ github.sha }}
      pr-number: "dev"
      tag: ${{ github.sha }}-dev
      target-branch: ${{ github.ref_name }}
    secrets: inherit
